### ISSUE TITLE
Error in 1_kallisto.smk

### ISSUE THREAD

**Issue by codylslater** [mckellardw/ref_snake#2]
I'm pretty sure all the executable paths are updated now for my configuration. Everything runs fine until I get to line 35 in 1_kallisto.smk (rule kb_velocity). I am getting the error below and am finding the error about a corrupted file a little cryptic. Any suggestions?

`Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Select jobs to execute...
Waiting at most 5 seconds for missing files.
MissingOutputException in rule kb_velocity in file /gpfs/commons/groups/vickovic_lab/cslater/code/ref_snake/rules/1_kallisto.smk, line 35:
Job 0 completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
out/homo_sapiens/genome/kb_velo/transcriptome.idx
Removing output files of failed job kb_velocity since they might be corrupted:
out/homo_sapiens/genome/kb_velo, out/homo_sapiens/genome/kb_velo/t2g.txt, out/homo_sapiens/genome/kb_velo/cdna.fa, out/homo_sapiens/genome/kb_velo/intron.fa, out/homo_sapiens/genome/kb_velo/cdna.t2c, out/homo_sapiens/genome/kb_velo/intron.t2c
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Removing output files of failed job kb_velocity since they might be corrupted:
out/homo_sapiens/genome/kb_velo
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-02-15T202658.101792.snakemake.log`

[2024-02-15T202658.101792.snakemake.log](https://github.com/mckellardw/ref_snake/files/14304318/2024-02-15T202658.101792.snakemake.log)

**Comment by mckellardw** [comment]
Could you share the log file from kb (`out/homo_sapiens/genome/kb_velo/kb_ref.log`)?

**Comment by codylslater** [comment]
I think that has been part of my trouble in debugging, that log get's deleted in the cleanup when it fails. I will save an alternate copy somewhere so I can see what's going on and upload it

**Comment by mckellardw** [comment]
Seems that this might be the underlying error from `kb-python` - 
```
subprocess.CalledProcessError: Command '/home/dwm269/miniconda3/envs/ref_snake/bin/kallisto index -i out/mus_musculus/genome/kb/transcriptome.idx -k 31 -t 8 -d out/mus_musculus/genome/raw/genome.fa.gz -T out/mus_musculus/genome/kb/tmp out/mus_musculus/genome/kb/cdna.fa' died with <Signals.SIGILL: 4>.
```
Mentioned here- https://github.com/pachterlab/kb_python/issues/239
I got the same error, tried recompiling both kallisto and bustools from binaries, and reinstalled from the dev branch on github (none fixed the error). Will wait for the fix to come through from `kb-python`

**Comment by mckellardw** [comment]
These issues should be fixed after recent pushes. 

Summary- when using a wrapped conda/mamba environment, don't specify an alternative path to kallisto, as it won't be compatible with kb
